kind: Service
apiVersion: v1
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: auth
          image: {{ .Values.image }}
          command:
            - "uvicorn"
          args:
            - "src.main:app"
            - "--reload"
            - "--host=0.0.0.0"
            - "--port=8001"
          ports:
            - containerPort: 8001
          imagePullPolicy: {{ .Values.imagePullPolicy }}
